{"version": 2, "width": 160, "height": 40, "timestamp": 1760921039, "env": {"SHELL": "/bin/bash", "TERM": "tmux-256color"}}
[0.009271, "o", "\u001b[?2004hroot@733bd092af77:/app# "]
[2.82288, "i", "clear\r"]
[2.824106, "o", "clear\r\n\u001b[?2004l\r"]
[2.826494, "o", "\u001b[H\u001b[J\u001b[3J"]
[2.827156, "o", "\u001b[?2004hroot@733bd092af77:/app# "]
[2.983345, "i", "bash /tests/run-tests.sh; tmux wait -S done\r"]
[2.98347, "o", "bash /tests/run-tests.sh; tmux wait -S done"]
[2.984592, "o", "\r\n\u001b[?2004l\r"]
[7.080583, "o", "Collecting pytest\r\n"]
[7.175927, "o", "  Downloading pytest-8.4.2-py3-none-any.whl.metadata (7.7 kB)\r\n"]
[7.267685, "o", "Collecting requests\r\n"]
[7.275435, "o", "  Downloading requests-2.32.5-py3-none-any.whl.metadata (4.9 kB)\r\n"]
[7.516454, "o", "Collecting psutil\r\n"]
[7.524459, "o", "  Downloading psutil-7.1.1-cp36-abi3-manylinux_2_12_x86_64.manylinux2010_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (23 kB)\r\n"]
[7.581656, "o", "Collecting iniconfig>=1 (from pytest)\r\n"]
[7.611145, "o", "  Downloading iniconfig-2.3.0-py3-none-any.whl.metadata (2.5 kB)\r\n"]
[7.676571, "o", "Collecting packaging>=20 (from pytest)\r\n"]
[7.682909, "o", "  Downloading packaging-25.0-py3-none-any.whl.metadata (3.3 kB)\r\n"]
[7.731574, "o", "Collecting pluggy<2,>=1.5 (from pytest)\r\n"]
[7.738456, "o", "  Downloading pluggy-1.6.0-py3-none-any.whl.metadata (4.8 kB)\r\n"]
[7.799098, "o", "Collecting pygments>=2.7.2 (from pytest)\r\n"]
[7.804334, "o", "  Downloading pygments-2.19.2-py3-none-any.whl.metadata (2.5 kB)\r\n"]
[8.054162, "o", "Collecting charset_normalizer<4,>=2 (from requests)\r\n"]
[8.092533, "o", "  Downloading charset_normalizer-3.4.4-cp313-cp313-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl.metadata (37 kB)\r\n"]
[8.173057, "o", "Collecting idna<4,>=2.5 (from requests)\r\n"]
[8.178799, "o", "  Downloading idna-3.11-py3-none-any.whl.metadata (8.4 kB)\r\n"]
[8.28147, "o", "Collecting urllib3<3,>=1.21.1 (from requests)\r\n"]
[8.287485, "o", "  Downloading urllib3-2.5.0-py3-none-any.whl.metadata (6.5 kB)\r\n"]
[8.347603, "o", "Collecting certifi>=2017.4.17 (from requests)\r\n"]
[8.355597, "o", "  Downloading certifi-2025.10.5-py3-none-any.whl.metadata (2.5 kB)\r\n"]
[8.381072, "o", "Downloading pytest-8.4.2-py3-none-any.whl (365 kB)"]
[8.381541, "o", "\r\n"]
[8.407442, "o", "Downloading requests-2.32.5-py3-none-any.whl (64 kB)"]
[8.407591, "o", "\r\n"]
[8.422548, "o", "Downloading psutil-7.1.1-cp36-abi3-manylinux_2_12_x86_64.manylinux2010_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl (290 kB)\r\n"]
[8.442602, "o", "Downloading certifi-2025.10.5-py3-none-any.whl (163 kB)\r\n"]
[8.456859, "o", "Downloading charset_normalizer-3.4.4-cp313-cp313-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl (153 kB)\r\n"]
[8.475564, "o", "Downloading idna-3.11-py3-none-any.whl (71 kB)\r\n"]
[8.489601, "o", "Downloading iniconfig-2.3.0-py3-none-any.whl (7.5 kB)\r\n"]
[8.501676, "o", "Downloading packaging-25.0-py3-none-any.whl (66 kB)\r\n"]
[8.51394, "o", "Downloading pluggy-1.6.0-py3-none-any.whl (20 kB)\r\n"]
[8.527966, "o", "Downloading pygments-2.19.2-py3-none-any.whl (1.2 MB)\r\n"]
[8.52861, "o", "\u001b[?25l"]
[8.53206, "o", "   \u001b[38;5;237m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\u001b[0m \u001b[32m0.0/1.2 MB\u001b[0m \u001b[31m?\u001b[0m eta \u001b[36m-:--:--\u001b[0m"]
[8.55562, "o", "\r\u001b[2K   \u001b[38;5;70m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\u001b[0m \u001b[32m1.2/1.2 MB\u001b[0m \u001b[31m55.7 MB/s\u001b[0m eta \u001b[36m0:00:00\u001b[0m\r\n\u001b[?25h"]
[8.561658, "o", "Downloading urllib3-2.5.0-py3-none-any.whl (129 kB)\r\n"]
[8.679101, "o", "Installing collected packages: urllib3, pygments, psutil, pluggy, packaging, iniconfig, idna, charset_normalizer, certifi, requests, pytest\r\n"]
[12.068309, "o", "Successfully installed certifi-2025.10.5 charset_normalizer-3.4.4 idna-3.11 iniconfig-2.3.0 packaging-25.0 pluggy-1.6.0 psutil-7.1.1 pygments-2.19.2 pytest-8.4.2 requests-2.32.5 urllib3-2.5.0\r\n"]
[12.068457, "o", "\u001b[33mWARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager, possibly rendering your system unusable.It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv. Use the --root-user-action option if you know what you are doing and want to suppress this warning.\u001b[0m\u001b[33m"]
[12.069468, "o", "\r\n"]
[12.071508, "o", "\u001b[0m"]
[12.445695, "o", "\r\n"]
[12.447517, "o", "\u001b[1m[\u001b[0m\u001b[34;49mnotice\u001b[0m\u001b[1;39;49m]\u001b[0m\u001b[39;49m A new release of pip is available: \u001b[0m\u001b[31;49m24.3.1\u001b[0m\u001b[39;49m -> \u001b[0m\u001b[32;49m25.2\u001b[0m\r\n\u001b[1m[\u001b[0m\u001b[34;49mnotice\u001b[0m\u001b[1;39;49m]\u001b[0m\u001b[39;49m To update, run: \u001b[0m\u001b[32;49mpip install --upgrade pip\u001b[0m\r\n"]
[13.362441, "o", "\u001b[1m===================================================================== test session starts ======================================================================\u001b[0m"]
[13.362552, "o", "\r\n"]
[13.362911, "o", "platform linux -- Python 3.13.1, pytest-8.4.2, pluggy-1.6.0 -- /usr/local/bin/python3.13"]
[13.363149, "o", "\r\n"]
[13.363508, "o", "cachedir: .pytest_cache"]
[13.36382, "o", "\r\n"]
[13.364087, "o", "rootdir: /tests"]
[13.364521, "o", "\r\n\u001b[1mcollecting ... \u001b[0m"]
[13.542952, "o", "\u001b[1m\rcollected 5 items                                                                                                                                              \u001b[0m"]
[13.543322, "o", "\r\n"]
[13.544636, "o", "\r\n"]
[13.544916, "o", "../tests/test_outputs.py::test_status_endpoint "]
[23.621639, "o", "\u001b[31mERROR\u001b[0m\u001b[31m                                                                                                     [ 20%]\u001b[0m"]
[23.622711, "o", "\r\n../tests/test_outputs.py::test_block_endpoint "]
[23.630837, "o", "\u001b[31mERROR\u001b[0m\u001b[31m                                                                                                      [ 40%]\u001b[0m"]
[23.631841, "o", "\r\n../tests/test_outputs.py::test_account_endpoint "]
[23.639559, "o", "\u001b[31mERROR\u001b[0m\u001b[31m                                                                                                    [ 60%]\u001b[0m"]
[23.640484, "o", "\r\n../tests/test_outputs.py::test_program_accounts_endpoint "]
[23.648056, "o", "\u001b[31mERROR\u001b[0m\u001b[31m                                                                                           [ 80%]\u001b[0m"]
[23.649047, "o", "\r\n../tests/test_outputs.py::test_transaction_endpoint_exists "]
[23.657256, "o", "\u001b[31mERROR\u001b[0m\u001b[31m                                                                                         [100%]\u001b[0m"]
[23.659842, "o", "\r\n\r\n"]
[23.660382, "o", "============================================================================ ERRORS ============================================================================\r\n\u001b[31m\u001b[1m____________________________________________________________ ERROR at setup of test_status_endpoint ____________________________________________________________\u001b[0m\r\n\r\n"]
[23.737984, "o", "    \u001b[0m\u001b[37m@pytest\u001b[39;49;00m.fixture(scope=\u001b[33m\"\u001b[39;49;00m\u001b[33mmodule\u001b[39;49;00m\u001b[33m\"\u001b[39;49;00m)\u001b[90m\u001b[39;49;00m\r\n    \u001b[94mdef\u001b[39;49;00m\u001b[90m \u001b[39;49;00m\u001b[92mservice_ready\u001b[39;49;00m():\u001b[90m\u001b[39;49;00m\r\n    \u001b[90m    \u001b[39;49;00m\u001b[33m\"\"\"Wait for service to be ready before running tests\"\"\"\u001b[39;49;00m\u001b[90m\u001b[39;49;00m\r\n        max_attempts = \u001b[94m10\u001b[39;49;00m\u001b[90m\u001b[39;49;00m\r\n        \u001b[94mfor\u001b[39;49;00m attempt \u001b[95min\u001b[39;49;00m \u001b[96mrange\u001b[39;49;00m(max_attempts):\u001b[90m\u001b[39;49;00m\r\n"]
[23.738348, "o", "            \u001b[94mtry\u001b[39;49;00m:\u001b[90m\u001b[39;49;00m\r\n                response = requests.get(\u001b[33mf\u001b[39;49;00m\u001b[33m\"\u001b[39;49;00m\u001b[33m{\u001b[39;49;00mBASE_URL\u001b[33m}\u001b[39;49;00m\u001b[33m/status\u001b[39;49;00m\u001b[33m\"\u001b[39;49;00m, timeout=\u001b[94m2\u001b[39;49;00m)\u001b[90m\u001b[39;49;00m\r\n                \u001b[94mif\u001b[39;49;00m response.status_code == \u001b[94m200\u001b[39;49;00m:\u001b[90m\u001b[39;49;00m\r\n                    \u001b[94mreturn\u001b[39;49;00m \u001b[94mTrue\u001b[39;49;00m\u001b[90m\u001b[39;49;00m\r\n"]
[23.738395, "o", "            \u001b[94mexcept\u001b[39;49;00m (requests.exceptions.ConnectionError, requests.exceptions.Timeout):\u001b[90m\u001b[39;49;00m\r\n                \u001b[94mpass\u001b[39;49;00m\u001b[90m\u001b[39;49;00m\r\n            time.sleep(\u001b[94m1\u001b[39;49;00m)\u001b[90m\u001b[39;49;00m\r\n    \u001b[90m\u001b[39;49;00m\r\n>       pytest.fail(\u001b[33m\"\u001b[39;49;00m\u001b[33mSolana service is not responding\u001b[39;49;00m\u001b[33m\"\u001b[39;49;00m)\u001b[90m\u001b[39;49;00m\r\n\u001b[1m\u001b[31mE       Failed: Solana service is not responding\u001b[0m\r\n\r\n\u001b[1m\u001b[31m/tests/test_outputs.py\u001b[0m:31: Failed\r\n\u001b[31m\u001b[1m____________________________________________________________ ERROR at setup of test_block_endpoint _____________________________________________________________\u001b[0m\r\n"]
[23.738595, "o", "\r\n"]
[23.741182, "o", "    \u001b[0m\u001b[37m@pytest\u001b[39;49;00m.fixture(scope=\u001b[33m\"\u001b[39;49;00m\u001b[33mmodule\u001b[39;49;00m\u001b[33m\"\u001b[39;49;00m)\u001b[90m\u001b[39;49;00m\r\n    \u001b[94mdef\u001b[39;49;00m\u001b[90m \u001b[39;49;00m\u001b[92mservice_ready\u001b[39;49;00m():\u001b[90m\u001b[39;49;00m\r\n    \u001b[90m    \u001b[39;49;00m\u001b[33m\"\"\"Wait for service to be ready before running tests\"\"\"\u001b[39;49;00m\u001b[90m\u001b[39;49;00m\r\n"]
[23.741911, "o", "        max_attempts = \u001b[94m10\u001b[39;49;00m\u001b[90m\u001b[39;49;00m\r\n        \u001b[94mfor\u001b[39;49;00m attempt \u001b[95min\u001b[39;49;00m \u001b[96mrange\u001b[39;49;00m(max_attempts):\u001b[90m\u001b[39;49;00m\r\n            \u001b[94mtry\u001b[39;49;00m:\u001b[90m\u001b[39;49;00m\r\n                response = requests.get(\u001b[33mf\u001b[39;49;00m\u001b[33m\"\u001b[39;49;00m\u001b[33m{\u001b[39;49;00mBASE_URL\u001b[33m}\u001b[39;49;00m\u001b[33m/status\u001b[39;49;00m\u001b[33m\"\u001b[39;49;00m, timeout=\u001b[94m2\u001b[39;49;00m)\u001b[90m\u001b[39;49;00m\r\n                \u001b[94mif\u001b[39;49;00m response.status_code == \u001b[94m200\u001b[39;49;00m:\u001b[90m\u001b[39;49;00m\r\n                    \u001b[94mreturn\u001b[39;49;00m \u001b[94mTrue\u001b[39;49;00m\u001b[90m\u001b[39;49;00m\r\n            \u001b[94mexcept\u001b[39;49;00m (requests.exceptions.ConnectionError, requests.exceptions.Timeout):\u001b[90m\u001b[39;49;00m\r\n                \u001b[94mpass\u001b[39;49;00m\u001b[90m\u001b[39;49;00m\r\n            time.sleep(\u001b[94m1\u001b[39;49;00m)\u001b[90m\u001b[39;49;00m\r\n    \u001b[90m\u001b[39;49;00m\r\n>       pytest.fail(\u001b[33m\"\u001b[39;49;00m\u001b[33mSolana service is not responding\u001b[39;49;00m\u001b[33m\"\u001b[39;49;00m)\u001b[90m\u001b[39;49;00m\r\n\u001b[1m\u001b[31mE       Failed: Solana service is not res"]
[23.74204, "o", "ponding\u001b[0m\r\n\r\n\u001b[1m\u001b[31m/tests/test_outputs.py\u001b[0m:31: Failed\r\n\u001b[31m\u001b[1m___________________________________________________________ ERROR at setup of test_account_endpoint ____________________________________________________________\u001b[0m\r\n\r\n"]
[23.744153, "o", "    \u001b[0m\u001b[37m@pytest\u001b[39;49;00m.fixture(scope=\u001b[33m\"\u001b[39;49;00m\u001b[33mmodule\u001b[39;49;00m\u001b[33m\"\u001b[39;49;00m)\u001b[90m\u001b[39;49;00m\r\n    \u001b[94mdef\u001b[39;49;00m\u001b[90m \u001b[39;49;00m\u001b[92mservice_ready\u001b[39;49;00m():\u001b[90m\u001b[39;49;00m\r\n    \u001b[90m    \u001b[39;49;00m\u001b[33m\"\"\"Wait for service to be ready before running tests\"\"\"\u001b[39;49;00m\u001b[90m\u001b[39;49;00m\r\n        max_attempts = \u001b[94m10\u001b[39;49;00m\u001b[90m\u001b[39;49;00m"]
[23.744608, "o", "\r\n        \u001b[94mfor\u001b[39;49;00m attempt \u001b[95min\u001b[39;49;00m \u001b[96mrange\u001b[39;49;00m(max_attempts):\u001b[90m\u001b[39;49;00m\r\n            \u001b[94mtry\u001b[39;49;00m:\u001b[90m\u001b[39;49;00m\r\n                response = requests.get(\u001b[33mf\u001b[39;49;00m\u001b[33m\"\u001b[39;49;00m\u001b[33m{\u001b[39;49;00mBASE_URL\u001b[33m}\u001b[39;49;00m\u001b[33m/status\u001b[39;49;00m\u001b[33m\"\u001b[39;49;00m, timeout=\u001b[94m2\u001b[39;49;00m)\u001b[90m\u001b[39;49;00m\r\n                \u001b[94mif\u001b[39;49;00m response.status_code == \u001b[94m200\u001b[39;49;00m:\u001b[90m\u001b[39;49;00m\r\n                    \u001b[94mreturn\u001b[39;49;00m \u001b[94mTrue\u001b[39;49;00m\u001b[90m\u001b[39;49;00m\r\n            \u001b[94mexcept\u001b[39;49;00m (requests.exceptions.ConnectionError, requests.exceptions.Timeout):\u001b[90m\u001b[39;49;00m\r\n                \u001b[94mpass\u001b[39;49;00m\u001b[90m\u001b[39;49;00m\r\n            time.sleep(\u001b[94m1\u001b[39;49;00m)\u001b[90m\u001b[39;49;00m\r\n    \u001b[90m\u001b[39;49;00m\r\n>       pytest.fail(\u001b[33m\"\u001b[39;49;00m\u001b[33mSolana service is not responding\u001b[39;49;00m\u001b[33m\"\u001b[39;49;00m)\u001b[90m\u001b[39;49;00m\r\n\u001b[1m\u001b[31mE       Failed: Solana service is not responding\u001b[0m\r\n\r\n\u001b[1m\u001b[31m/tests/test_outputs.py\u001b[0m:31: Fa"]
[23.744668, "o", "iled\r\n\u001b[31m\u001b[1m_______________________________________________________ ERROR at setup of test_program_accounts_endpoint _______________________________________________________\u001b[0m\r\n\r\n"]
[23.746812, "o", "    \u001b[0m\u001b[37m@pytest\u001b[39;49;00m.fixture(scope=\u001b[33m\"\u001b[39;49;00m\u001b[33mmodule\u001b[39;49;00m\u001b[33m\"\u001b[39;49;00m)\u001b[90m\u001b[39;49;00m\r\n    \u001b[94mdef\u001b[39;49;00m\u001b[90m \u001b[39;49;00m\u001b[92mservice_ready\u001b[39;49;00m():\u001b[90m\u001b[39;49;00m\r\n    \u001b[90m    \u001b[39;49;00m\u001b[33m\"\"\"Wait for service to be ready before running tests\"\"\"\u001b[39;49;00m\u001b[90m\u001b[39;49;00m\r\n        max_attempts = \u001b[94m10\u001b[39;49;00m\u001b[90m\u001b[39;49;00m\r\n"]
[23.747205, "o", "        \u001b[94mfor\u001b[39;49;00m attempt \u001b[95min\u001b[39;49;00m \u001b[96mrange\u001b[39;49;00m(max_attempts):\u001b[90m\u001b[39;49;00m\r\n            \u001b[94mtry\u001b[39;49;00m:\u001b[90m\u001b[39;49;00m\r\n                response = requests.get(\u001b[33mf\u001b[39;49;00m\u001b[33m\"\u001b[39;49;00m\u001b[33m{\u001b[39;49;00mBASE_URL\u001b[33m}\u001b[39;49;00m\u001b[33m/status\u001b[39;49;00m\u001b[33m\"\u001b[39;49;00m, timeout=\u001b[94m2\u001b[39;49;00m)\u001b[90m\u001b[39;49;00m\r\n                \u001b[94mif\u001b[39;49;00m response.status_code == \u001b[94m200\u001b[39;49;00m:\u001b[90m\u001b[39;49;00m\r\n                    \u001b[94mreturn\u001b[39;49;00m \u001b[94mTrue\u001b[39;49;00m\u001b[90m\u001b[39;49;00m\r\n            \u001b[94mexcept\u001b[39;49;00m (requests.exceptions.ConnectionError, requests.exceptions.Timeout):\u001b[90m\u001b[39;49;00m\r\n                \u001b[94mpass\u001b[39;49;00m\u001b[90m\u001b[39;49;00m\r\n            time.sleep(\u001b[94m1\u001b[39;49;00m)\u001b[90m\u001b[39;49;00m\r\n    \u001b[90m\u001b[39;49;00m\r\n>       pytest.fail(\u001b[33m\"\u001b[39;49;00m\u001b[33mSolana service is not responding\u001b[39;49;00m\u001b[33m\"\u001b[39;49;00m)\u001b[90m\u001b[39;49;00m\r\n\u001b[1m\u001b[31mE       Failed: Solana service is not responding\u001b[0m\r\n\r\n\u001b[1m\u001b[31m/tests/test_outputs.py\u001b[0m:31: Fail"]
[23.747285, "o", "ed\r\n\u001b[31m\u001b[1m______________________________________________________ ERROR at setup of test_transaction_endpoint_exists ______________________________________________________\u001b[0m\r\n\r\n"]
[23.749757, "o", "    \u001b[0m\u001b[37m@pytest\u001b[39;49;00m.fixture(scope=\u001b[33m\"\u001b[39;49;00m\u001b[33mmodule\u001b[39;49;00m\u001b[33m\"\u001b[39;49;00m)\u001b[90m\u001b[39;49;00m\r\n    \u001b[94mdef\u001b[39;49;00m\u001b[90m \u001b[39;49;00m\u001b[92mservice_ready\u001b[39;49;00m():\u001b[90m\u001b[39;49;00m\r\n    \u001b[90m    \u001b[39;49;00m\u001b[33m\"\"\"Wait for service to be ready before running tests\"\"\"\u001b[39;49;00m\u001b[90m\u001b[39;49;00m\r\n        max_attempts = \u001b[94m10\u001b[39;49;00m\u001b[90m\u001b[39;49;00m\r\n"]
[23.75017, "o", "        \u001b[94mfor\u001b[39;49;00m attempt \u001b[95min\u001b[39;49;00m \u001b[96mrange\u001b[39;49;00m(max_attempts):\u001b[90m\u001b[39;49;00m\r\n            \u001b[94mtry\u001b[39;49;00m:\u001b[90m\u001b[39;49;00m\r\n                response = requests.get(\u001b[33mf\u001b[39;49;00m\u001b[33m\"\u001b[39;49;00m\u001b[33m{\u001b[39;49;00mBASE_URL\u001b[33m}\u001b[39;49;00m\u001b[33m/status\u001b[39;49;00m\u001b[33m\"\u001b[39;49;00m, timeout=\u001b[94m2\u001b[39;49;00m)\u001b[90m\u001b[39;49;00m\r\n                \u001b[94mif\u001b[39;49;00m response.status_code == \u001b[94m200\u001b[39;49;00m:\u001b[90m\u001b[39;49;00m\r\n                    \u001b[94mreturn\u001b[39;49;00m \u001b[94mTrue\u001b[39;49;00m\u001b[90m\u001b[39;49;00m\r\n            \u001b[94mexcept\u001b[39;49;00m (requests.exceptions.ConnectionError, requests.exceptions.Timeout):\u001b[90m\u001b[39;49;00m"]
[23.750227, "o", "\r\n                \u001b[94mpass\u001b[39;49;00m\u001b[90m\u001b[39;49;00m\r\n            time.sleep(\u001b[94m1\u001b[39;49;00m)\u001b[90m\u001b[39;49;00m\r\n    \u001b[90m\u001b[39;49;00m\r\n>       pytest.fail(\u001b[33m\"\u001b[39;49;00m\u001b[33mSolana service is not responding\u001b[39;49;00m\u001b[33m\"\u001b[39;49;00m)\u001b[90m\u001b[39;49;00m\r\n\u001b[1m\u001b[31mE       Failed: Solana service is not responding\u001b[0m\r\n\r\n\u001b[1m\u001b[31m/tests/test_outputs.py\u001b[0m:31: Failed\r\n"]
[23.751718, "o", "\u001b[36m\u001b[1m=================================================================== short test summary info ====================================================================\u001b[0m\r\n\u001b[31mERROR\u001b[0m ../tests/test_outputs.py::\u001b[1mtest_status_endpoint\u001b[0m - Failed: Solana service is not responding\r\n"]
[23.752011, "o", "\u001b[31mERROR\u001b[0m ../tests/test_outputs.py::\u001b[1mtest_block_endpoint\u001b[0m - Failed: Solana service is not responding\r\n\u001b[31mERROR\u001b[0m ../tests/test_outputs.py::\u001b[1mtest_account_endpoint\u001b[0m - Failed: Solana service is not responding\r\n\u001b[31mERROR\u001b[0m ../tests/test_outputs.py::\u001b[1mtest_program_accounts_endpoint\u001b[0m - Failed: Solana service is not responding\r\n\u001b[31mERROR\u001b[0m ../tests/test_outputs.py::\u001b[1mtest_transaction_endpoint_exists\u001b[0m - Failed: Solana service is not responding\r\n"]
[23.752053, "o", "\u001b[31m====================================================================== \u001b[31m\u001b[1m5 errors\u001b[0m\u001b[31m in 10.39s\u001b[0m\u001b[31m ======================================================================\u001b[0m\r\n"]
[23.979913, "o", "\u001b[?2004h"]
[23.980097, "o", "root@733bd092af77:/app# "]
[24.268313, "i", "\u0004"]
[24.269192, "o", "\u001b[?2004l\r\r\nexit\r\n"]
